package com.marko.skriptarnica.common

//CourseFragment
const val STRUCNI_STUDIJ = 1
const val PREDDIPLOMSKI_STUDIJ = 2
const val DIPLOMSKI_STUDIJ = 3

//SubjectFragment
const val RACUNARSTVO_1_GODINA = 1
const val RACUNARSTVO_2_GODINA = 2
const val RACUNARSTVO_3_GODINA = 3
const val AUTOMATIKA_1_GODINA = 4
const val AUTOMATIKA_2_GODINA = 5
const val AUTOMATIKA_3_GODINA = 6
const val ELEKTROENERGETIKA_1_GODINA = 7
const val ELEKTROENERGETIKA_2_GODINA = 8
const val ELEKTROENERGETIKA_3_GODINA = 9
const val ELEKTROTEHNIKA_1_GODINA = 10
const val ELEKTROTEHNIKA_2_GODINA_EE = 11
const val ELEKTROTEHNIKA_2_GODINA_KI = 12
const val ELEKTROTEHNIKA_3_GODINA_EE = 13
const val ELEKTROTEHNIKA_3_GODINA_KI = 14
const val PREDDIPL_RACUNARSTVO_1_GODINA = 15
const val PREDDIPL_RACUNARSTVO_2_GODINA = 16
const val PREDDIPL_RACUNARSTVO_3_GODINA = 17
const val RACUNALNO_INZENJERSTVO_1_GODINA = 18
const val RACUNALNO_INZENJERSTVO_2_GODINA = 19
const val ROBOTIKA_UMJETNA_INTELIGENCIJA_1_GODINA = 20
const val ROBOTIKA_UMJETNA_INTELIGENCIJA_2_GODINA = 21
const val PROGRAMSKO_INZENJERSTVO_1_GODINA = 22
const val PROGRAMSKO_INZENJERSTVO_2_GODINA = 23
const val INFORMACIJSKE_PODATKOVNE_ZNANOSTI_1_GODINA = 24
const val INFORMACIJSKE_PODATKOVNE_ZNANOSTI_2_GODINA = 25
const val KOMUNIKACIJSKE_TEHNOLOGIJE_1_GODINA = 26
const val KOMUNIKACIJSKE_TEHNOLOGIJE_2_GODINA = 27
const val MREZNE_TEHNOLOGIJE_1_GODINA = 28
const val MREZNE_TEHNOLOGIJE_2_GODINA = 29
const val ELEKTROENERGETSKI_SUSTAVI_1_GODINA = 30
const val ELEKTROENERGETSKI_SUSTAVI_2_GODINA = 31
const val ODRZIVA_ELEKTROENERGETIKA_1_GODINA = 32
const val ODRZIVA_ELEKTROENERGETIKA_2_GODINA = 33
const val INDUSTRIJSKA_ELEKTROENERGETIKA_1_GODINA = 34
const val INDUSTRIJSKA_ELEKTROENERGETIKA_2_GODINA = 35
const val AUTOMOBILSKO_RACUNARSTVO_ENG_1_GODINA = 36
const val AUTOMOBILSKO_RACUNARSTVO_ENG_2_GODINA = 37
const val AUTOMOBILSKO_RACUNARSTVO_1_GODINA = 38
const val AUTOMOBILSKO_RACUNARSTVO_2_GODINA = 39